# Generated by Django 2.2.12 on 2020-04-24 12:37

from django.db import migrations, models
import localflavor.ua.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', localflavor.ua.models.UARegionField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/users/%Y/%m/%d'),
        ),
    ]
