# Generated by Django 2.2.12 on 2020-04-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_auto_20200424_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
