# Generated by Django 2.2.12 on 2020-05-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_auto_20200514_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='apartment_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='house_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
