# Generated by Django 2.2.12 on 2020-06-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_auto_20200516_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/users/%Y/%m/%d'),
        ),
    ]
