# Generated by Django 2.2.4 on 2020-04-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('carts', '0005_auto_20200409_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_in',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
