# Generated by Django 2.2.12 on 2020-04-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20200409_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price_total',
            new_name='price',
        ),
    ]
