# Generated by Django 2.2.12 on 2020-04-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
    ]
