# Generated by Django 2.2.12 on 2020-05-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='delivery_city',
            new_name='shipment_address_city',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='delivery_apartment',
            new_name='shipment_adress_apartment',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='delivery_house',
            new_name='shipment_adress_house',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='delivery_street',
            new_name='shipment_adress_street',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='delivery_comment',
            new_name='shipment_comment',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_options',
        ),
        migrations.AddField(
            model_name='shipment',
            name='variants',
            field=models.CharField(choices=[('Pick_up', 'Pick up'), ('Courier', 'Courier'), ('Nova_poshta', 'Nova Poshta')], default='Pick_up', max_length=20),
        ),
    ]
