# Generated by Django 2.2.12 on 2020-05-01 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20200501_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
