# Generated by Django 2.2.12 on 2020-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_shipment_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_adress_apartment',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_comment',
            field=models.TextField(blank=True),
        ),
    ]
