# Generated by Django 2.2.12 on 2020-05-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='invoice_id',
        ),
    ]
