# Generated by Django 2.2.12 on 2020-05-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_remove_shipment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_adress_apartment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
