# Generated by Django 2.2.12 on 2020-05-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_auto_20200514_1643'),
        ('shipments', '0011_auto_20200507_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='user_profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_profiles.UserProfile'),
        ),
    ]
