# Generated by Django 2.2.12 on 2020-05-27 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_auto_20200507_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
