# Generated by Django 2.2.12 on 2020-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_auto_20200515_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='shipment',
            name='id',
            field=models.AutoField(auto_created=True, default=345345, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
