# Generated by Django 2.2.12 on 2020-06-04 04:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_auto_20200527_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
