# Generated by Django 2.2.4 on 2020-06-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_auto_20200605_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='variants',
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_status_type',
            field=models.CharField(choices=[('PACKING', 'Packing'), ('PICKED_UP', 'Picked up by courier'), ('ON_THE_WAY', 'On the way'), ('DELIVERED', 'Delivered')], default='PACKING', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('PICK_UP', 'Pick up'), ('COURIER', 'Courier'), ('NOVA_POSHTA', 'Nova Poshta')], default='PICK_UP', max_length=20),
        ),
    ]
