# Generated by Django 2.2.4 on 2020-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_auto_20200611_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_status_type',
            field=models.CharField(choices=[('PACKING', 'Packing'), ('PICKED_UP', 'Picked up by courier'), ('ON_THE_WAY', 'On the way'), ('DELIVERED', 'Delivered')], default='PACKING', max_length=50),
        ),
    ]
