# Generated by Django 2.2.12 on 2020-04-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='size',
            field=models.CharField(choices=[('min', 'min'), ('max', 'max'), ('middle', 'middle')], default='middle', max_length=100),
        ),
        migrations.AddField(
            model_name='gallery',
            name='size_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='size_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/%Y/%m/%d'),
        ),
    ]
