# Generated by Django 2.2.12 on 2020-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20200430_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='size_x',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='size_y',
            field=models.IntegerField(default=150),
        ),
    ]
