# Generated by Django 2.2.12 on 2020-05-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='variants',
            field=models.CharField(choices=[('View', 'View'), ('buy', 'Buy'), ('add_to_cart', 'Add to cart')], default='View', max_length=20),
        ),
    ]
