# Generated by Django 2.2.12 on 2020-05-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_stats_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='variants',
        ),
    ]
