# Generated by Django 2.2.12 on 2020-04-19 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20200416_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('raw_response', models.TextField()),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('processed_ok', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('paysystem', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('completed', 'completed'), ('suspended', 'suspended'), ('declined', 'declined')], default='submitted', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
