# Generated by Django 2.2.12 on 2020-04-23 13:38

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200419_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=django_fsm.FSMField(choices=[('submitted', 'submitted'), ('processing', 'processing'), ('completed', 'completed'), ('suspended', 'suspended'), ('declined', 'declined')], default=('submitted', 'submitted'), max_length=50),
        ),
    ]
