# Generated by Django 2.2.12 on 2020-04-29 19:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200423_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='paysystem',
            new_name='paymentsystem',
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='payer_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='receiver_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsystemlog',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='paymentsystemlog',
            name='raw_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
