# Generated by Django 2.2.12 on 2020-05-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200430_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentsystemlog',
            old_name='payer_id',
            new_name='SHOPORDERNUMBER',
        ),
        migrations.RenameField(
            model_name='paymentsystemlog',
            old_name='processed_at',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='paymentsystemlog',
            old_name='order',
            new_name='shopOrderNumber',
        ),
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='processed_ok',
        ),
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='payments',
            name='billAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='BILL_AMOUNT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='RESULT',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='SHOPBILLID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='billAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='payeeId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paymentsystem',
            field=models.CharField(choices=[('portmone', 'portmone'), ('cash', 'cash')], default='portmone', max_length=10),
        ),
    ]
