# Generated by Django 2.2.12 on 2020-05-14 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200514_1607'),
        ('payments', '0004_auto_20200430_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentsystemlog',
            old_name='processed_at',
            new_name='dt',
        ),
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='payer_id',
        ),
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='processed_ok',
        ),
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='paymentsystemlog',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='payments',
            name='billAmount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='BILL_AMOUNT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='RESULT',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='SHOPBILLID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='SHOPORDERNUMBER',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='billAmount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='payeeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentsystemlog',
            name='shopOrderNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paymentsystem',
            field=models.CharField(choices=[('portmone', 'portmone'), ('cash', 'cash')], default='portmone', max_length=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
