# Generated by Django 2.2.12 on 2020-05-21 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200514_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='billAmount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentsystemlog',
            name='BILL_AMOUNT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentsystemlog',
            name='RESULT',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentsystemlog',
            name='SHOPBILLID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentsystemlog',
            name='SHOPORDERNUMBER',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsystemlog',
            name='billAmount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentsystemlog',
            name='payeeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentsystemlog',
            name='shopOrderNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
        ),
    ]
