# Generated by Django 2.2.4 on 2020-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200406_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default='', max_length=15, verbose_name='Артикул'),
        ),
    ]
