# Generated by Django 2.2.4 on 2020-04-11 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20200409_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000, verbose_name='Опис')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('term', models.DateTimeField(blank=True, verbose_name='Термін до')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kit', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Galleries',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.CharField(blank=True, max_length=500, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_sn',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sn', to='products.Product', verbose_name='Відгук'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=5000, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(db_index=True, default='', max_length=15, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=5000, verbose_name='Відгук'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='kit',
            name='kits_products_sn',
            field=models.ManyToManyField(related_name='kits_products_sn', to='products.Product'),
        ),
    ]
