# Generated by Django 2.2.12 on 2020-04-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200411_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='kit',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='kits_products_sn',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_sn',
        ),
        migrations.AddField(
            model_name='kit',
            name='kits_product',
            field=models.ManyToManyField(related_name='kits_product', to='products.Product'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.Product', verbose_name='Відгук'),
        ),
    ]
