# Generated by Django 2.2.12 on 2020-04-30 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200423_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='kits_product',
        ),
        migrations.AddField(
            model_name='kit',
            name='products',
            field=models.ManyToManyField(related_name='kits', to='products.Product', verbose_name='Продукти'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
