# Generated by Django 2.2.12 on 2020-04-12 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('orders', '0001_initial'), ('orders', '0002_auto_20200408_2128'), ('orders', '0003_auto_20200409_1733'), ('orders', '0004_auto_20200409_1735'), ('orders', '0003_auto_20200409_1656'), ('orders', '0004_auto_20200409_1702'), ('orders', '0005_merge_20200412_0722'), ('orders', '0006_auto_20200412_0723')]

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_payment', models.CharField(choices=[('Cash', 'Cash'), ('Portmone', 'Portmone')], default='', max_length=100)),
                ('order_shipment', models.CharField(choices=[('Pickup', 'Pickup'), ('New Post', 'New Post')], default='', max_length=100)),
                ('order_status', models.CharField(choices=[('New order', 'New order'), ('Order processing', 'Order processing'), ('Packing', 'Packing'), ('Finished', 'Finished')], default='New order', max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_products', models.PositiveSmallIntegerField(default=1)),
                ('discont', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
    ]
