# Generated by Django 2.2.12 on 2020-04-17 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_squashed_0006_auto_20200412_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Portmone', 'Portmone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_shipment',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('New Post', 'New Post')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
    ]
