# Generated by Django 2.2.12 on 2020-04-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_squashed_0006_auto_20200412_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Portmone', 'Portmone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_shipment',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('New Post', 'New Post')], max_length=100),
        ),
    ]
