# Generated by Django 2.2.4 on 2020-04-09 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200408_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('7c6bf0e4-a020-495b-8392-8dc23bf9284b')),
        ),
    ]
