# Generated by Django 2.2.12 on 2020-05-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_cost'),
        ('orders', '0002_auto_20200416_1659'),
    ]

    operations = [
    ]
