# Generated by Django 2.2.12 on 2020-04-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200409_1735'),
        ('orders', '0004_auto_20200409_1702'),
    ]

    operations = [
    ]
