# Generated by Django 2.2.4 on 2020-04-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_of_products',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
