# Generated by Django 2.2.12 on 2020-05-16 17:45

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200512_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=apps.orders.models.Order.short_order_number, max_length=30),
        ),
    ]
