# Generated by Django 2.2.12 on 2020-05-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200514_1607'),
        ('orders', '0006_auto_20200512_2019'),
    ]

    operations = [
    ]
