# Generated by Django 2.2.12 on 2020-05-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200516_2045'),
        ('orders', '0007_merge_20200516_2117'),
    ]

    operations = [
    ]
